// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShopApplication;

namespace ShopApplication.Migrations
{
    [DbContext(typeof(ItemContext))]
    [Migration("20210909053303_initialMigration")]
    partial class initialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ShopApplication.ItemsList", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ItemsListItemId")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductNumber")
                        .HasColumnType("int");

                    b.Property<int>("ProductPrice")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("ItemId");

                    b.HasIndex("ItemsListItemId");

                    b.ToTable("itemsLists");

                    b.HasData(
                        new
                        {
                            ItemId = 101,
                            ProductName = "XXX",
                            ProductNumber = 1,
                            ProductPrice = 12,
                            Quantity = 3
                        },
                        new
                        {
                            ItemId = 102,
                            ProductName = "YYY",
                            ProductNumber = 2,
                            ProductPrice = 15,
                            Quantity = 0
                        },
                        new
                        {
                            ItemId = 103,
                            ProductName = "ZZZ",
                            ProductNumber = 3,
                            ProductPrice = 20,
                            Quantity = 2
                        });
                });

            modelBuilder.Entity("ShopApplication.ItemsList", b =>
                {
                    b.HasOne("ShopApplication.ItemsList", null)
                        .WithMany("itemsLists")
                        .HasForeignKey("ItemsListItemId");
                });

            modelBuilder.Entity("ShopApplication.ItemsList", b =>
                {
                    b.Navigation("itemsLists");
                });
#pragma warning restore 612, 618
        }
    }
}
